export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

export const SAVE_USER_CREDENTIALS = 'SAVE_USER_CREDENTIALS';

export const SAVE_USER_CORRECT_ANSWER = 'SAVE_USER_CORRECT_ANSWER';

export const RESET_USER_SCORE = 'RESET_USER_SCORE';
